# Generated by Django 4.2.5 on 2023-09-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['reg_date'], 'verbose_name': 'Читатели', 'verbose_name_plural': 'Читатели'},
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, height_field='300', upload_to='profiles/', width_field='200'),
        ),
    ]
