# Generated by Django 4.2.5 on 2023-09-13 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publishing_house', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('number', models.IntegerField()),
                ('issn', models.CharField(max_length=8, unique=True)),
                ('total_amount', models.IntegerField()),
                ('added_to_lib_date', models.DateField(auto_now_add=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.genres')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('isbn', models.CharField(max_length=10, unique=True)),
                ('total_amount', models.IntegerField()),
                ('in_stock', models.IntegerField(default=models.IntegerField())),
                ('gived_away', models.IntegerField(default=0)),
                ('added_to_lib_date', models.DateField(auto_now_add=True)),
                ('is_givedaway', models.BooleanField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.genres')),
            ],
        ),
    ]
