# Generated by Django 4.2.5 on 2023-09-19 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_category_publishinghouse_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'Книги', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'ordering': ['id'], 'verbose_name': 'Жанры', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='magazine',
            options={'ordering': ['title'], 'verbose_name': 'Журналы', 'verbose_name_plural': 'Журналы'},
        ),
        migrations.AlterModelOptions(
            name='publishinghouse',
            options={'ordering': ['id'], 'verbose_name': 'Издательства', 'verbose_name_plural': 'Издательства'},
        ),
        migrations.AlterField(
            model_name='book',
            name='added_to_lib_date',
            field=models.DateField(auto_now_add=True, verbose_name='Добавлена'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='books.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='books.genres', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='book',
            name='in_stock',
            field=models.IntegerField(default=models.IntegerField(verbose_name='Всего'), verbose_name='В библиотеке'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='books.publishinghouse', verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_amount',
            field=models.IntegerField(verbose_name='Всего'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
    ]
