# Generated by Django 4.2.5 on 2023-09-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_testmodel_alter_book_is_givedaway'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_givedaway',
        ),
        migrations.AlterField(
            model_name='book',
            name='gived_away',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='in_stock',
            field=models.IntegerField(blank=True, default=models.IntegerField(verbose_name='Всего'), null=True, verbose_name='В библиотеке'),
        ),
    ]
