# Generated by Django 4.2.5 on 2023-09-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_is_givedaway_alter_book_gived_away_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='gived_away',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
