# Generated by Django 4.2.5 on 2023-10-05 16:33

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_gived_away'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
        migrations.AddField(
            model_name='genres',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='in_stock',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='В библиотеке'),
        ),
    ]
