# Generated by Django 4.2.5 on 2023-10-05 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_category_slug_genres_slug_alter_book_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='in_stock',
        ),
    ]
